name: Karan Goel
description: Just my thoughts
meta_description: "Karan Goel's blog"

markdown: redcarpet
pygments: true
logo: false
paginate: 15

# Details for the RSS feed generator
url:            'http://localhost:4000'
author:         'Karan Goel'
