markdown: redcarpet
pygments: true
logo: false

title: Karan Goel
tagline: Blog
description: I like to make things.
url: http://karan.github.io/

# author:
#     name: 'Karan Goel'
#     url: https://www.goel.im

paginate: 5
