# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Karan Goel
tagline:          'Blog'
description:      'Thoughts on programming and life.'
url:              http://karan.github.io
paginate:         5

author:
  name:           'Karan Goel'
  url:             http://www.goel.im
  twitter:         https://twitter.com/TheKaranGoel
  github:          http://github.com/karan 

# Custom vars
version:          1.0.0
